# Generated by Django 4.2 on 2025-06-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classstruct',
            options={'verbose_name': 'Классификатор', 'verbose_name_plural': 'Классификатор'},
        ),
    ]
