# Generated by Django 4.2 on 2025-06-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_parclass_parclass_parclass_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classstruct",
            name="short_name",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Сокращенное название класса",
            ),
        ),
    ]
