# Generated by Django 4.2 on 2026-06-25 15:28

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_alter_parclass_max_value_alter_parclass_min_value"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_CYCLE,
            reverse_sql=DatabaseFunctions.DROP_CHECK_CYCLE
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.DELETE_CLASS_AND_DESCENDANTS,
            reverse_sql=DatabaseFunctions.DROP_DELETE_CLASS_AND_DESCENDANTS,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.FIND_GR_GR,
            reverse_sql=DatabaseFunctions.DROP_FIND_GR_GR,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.GET_TERMINAL_CLASSES,
            reverse_sql=DatabaseFunctions.DROP_GET_TERMINAL_CLASSES,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.ADD_PARAMETR_TO_CLASS,
            reverse_sql=DatabaseFunctions.DROP_ADD_PARAMETR_TO_CLASS,
        ),
    ]
