# Generated by Django 4.2 on 2026-06-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_alter_parclass_max_value_alter_parclass_min_value"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION check_class_struct_cycles(cls_id integer, main_cls_id integer) RETURNS boolean
                    LANGUAGE plpgsql
                AS
                $$
                    DECLARE
                        rec RECORD;
                        visited INTEGER[];      -- массив для хранения посещённых идентификаторов
                        parent_id INTEGER;      -- текущий родительский идентификатор
                    BEGIN
                
                    CREATE TEMP TABLE TEMP_CLASS_STRUCT(
                        CLASS_ID INTEGER PRIMARY KEY,
                        MAIN_CLASS INTEGER,
                        FOREIGN KEY (MAIN_CLASS) REFERENCES TEMP_CLASS_STRUCT(CLASS_ID)
                    ) ON COMMIT DROP;
                    
                    INSERT INTO TEMP_CLASS_STRUCT 
                    SELECT classes_classstruct.id, classes_classstruct.main_class_id FROM classes_classstruct;
                
                    UPDATE TEMP_CLASS_STRUCT
                    SET MAIN_CLASS = MAIN_CLS_ID
                    WHERE TEMP_CLASS_STRUCT.CLASS_ID = CLS_ID;
                    
                        -- перебираем все записи таблицы
                        FOR rec IN SELECT class_id, main_class FROM TEMP_CLASS_STRUCT LOOP
                                visited := ARRAY[rec.class_id];  -- начинаем с текущего класса
                                parent_id := rec.main_class;
                
                                -- идём по цепочке родителей, пока не достигнем конца (NULL)
                                WHILE parent_id IS NOT NULL LOOP
                                        -- если родитель уже встречался, значит, обнаружен цикл
                                        IF parent_id = ANY(visited) THEN
                                            RETURN TRUE;
                                        END IF;
                
                                        -- добавляем родителя в массив посещённых
                                        visited := visited || parent_id;
                
                                        -- переходим к следующему родителю
                                        SELECT main_class INTO parent_id
                                        FROM TEMP_CLASS_STRUCT
                                        WHERE class_id = parent_id;
                                    END LOOP;
                            END LOOP;
                
                        -- если цикл не найден, возвращаем false
                        RETURN FALSE;
                    END;
                $$;
            """,
            reverse_sql="DROP FUNCTION check_class_struct_cycles(integer, integer);",
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION delete_class_and_descendants(_node_id integer) RETURNS integer
                    LANGUAGE plpgsql
                AS
                $$
                DECLARE
                    deleted_count INTEGER;
                BEGIN
                    -- Проверяем, что класс с данным идентификатором существует
                    IF NOT EXISTS (SELECT 1 FROM classes_classstruct WHERE classes_classstruct.id = _node_id) THEN
                        RAISE EXCEPTION 'Класс с идентификатором % не найден', _node_id;
                    END IF;
                
                    -- С помощью рекурсии собираем идентификаторы всех классов,
                    -- которые являются потомками указанного класса, включая его самого.
                    WITH RECURSIVE subtree AS (
                        SELECT classes_classstruct.id
                        FROM classes_classstruct
                        WHERE classes_classstruct.id = _node_id
                
                        UNION ALL
                
                        SELECT child.id
                        FROM classes_classstruct child
                                 INNER JOIN subtree parent ON child.main_class_id = parent.id
                    )
                    -- Удаляем все записи, идентификаторы которых найдены в поддереве
                    DELETE FROM classes_classstruct
                    WHERE classes_classstruct.id IN (SELECT classes_classstruct.id FROM subtree);
                
                    -- Получаем количество удалённых строк
                    GET DIAGNOSTICS deleted_count = ROW_COUNT;
                    RETURN deleted_count;
                END;
                $$;
            """,
            reverse_sql="DROP FUNCTION delete_class_and_descendants(integer);",
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION find_gr_gr(prod_class_id integer)
                    RETURNS TABLE(class_id bigint, main_class bigint, name character varying, base_ei bigint)
                    LANGUAGE plpgsql
                AS
                $$
                BEGIN
                    IF NOT EXISTS(SELECT 1 FROM classes_classstruct
                                       WHERE classes_classstruct.id = prod_class_id) THEN
                    RAISE EXCEPTION 'Такого класса не существует!';
                ELSE
                    RETURN QUERY
                        SELECT classes_classstruct.id, classes_classstruct.main_class_id, classes_classstruct.name, classes_classstruct.base_ei_id
                        FROM classes_classstruct
                        WHERE classes_classstruct.id = prod_class_id
                        UNION
                        (
                            WITH RECURSIVE r AS(
                                SELECT classes_classstruct.id, classes_classstruct.main_class_id, classes_classstruct.name, classes_classstruct.base_ei_id
                                FROM classes_classstruct
                                WHERE classes_classstruct.main_class_id = prod_class_id
                
                                UNION
                
                                SELECT classes_classstruct.id, classes_classstruct.main_class_id, classes_classstruct.name, classes_classstruct.base_ei_id
                                FROM classes_classstruct
                                         JOIN r
                                              ON classes_classstruct.main_class_id = r.id
                            )
                            SELECT * FROM r);
                   end if;
                end;
                $$;
            """,
            reverse_sql="DROP FUNCTION find_gr_gr(integer);",
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION get_terminal_classes(_start_class integer) RETURNS SETOF classes_classstruct
                    LANGUAGE plpgsql
                AS
                $$
                BEGIN
                    -- Проверяем, существует ли заданный класс
                    IF NOT EXISTS (SELECT 1 FROM classes_classstruct WHERE classes_classstruct.id = _start_class) THEN
                        RAISE EXCEPTION 'Класс с идентификатором % не найден', _start_class;
                    END IF;
                
                    RETURN QUERY
                        WITH RECURSIVE class_tree AS (
                            -- Начало рекурсии: выбран заданный класс
                            SELECT *
                            FROM classes_classstruct
                            WHERE classes_classstruct.id = _start_class
                
                            UNION ALL
                
                            -- Рекурсивное добавление: ищем потомков текущих вершин
                            SELECT child.*
                            FROM classes_classstruct child
                                     INNER JOIN class_tree parent ON child.MAIN_CLASS_ID = parent.id
                        )
                        -- Выбираем те вершины, у которых нет потомков
                        SELECT ct.*
                        FROM class_tree ct
                        WHERE NOT EXISTS (
                            SELECT 1 FROM classes_classstruct c
                            WHERE c.MAIN_CLASS_id = ct.id
                        );
                END;
                $$;
            """,
            reverse_sql="DROP FUNCTION get_terminal_classes(integer);",
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION to_add_parametr_to_class(cls_id integer, parametr_id integer, min_val double precision, max_val double precision) RETURNS integer
                    LANGUAGE plpgsql
                AS
                $$
                  DECLARE 
                    f_result INTEGER;
                    parametr_record RECORD;
                    parametr_tp INTEGER;
                    enum_parent_node_id INTEGER;
                    product_classes_parent_node_id INTEGER;
                    cls_ids integer[];
                  BEGIN
                    enum_parent_node_id := 14;
                    IF NOT EXISTS(SELECT * FROM classes_classstruct WHERE classes_classstruct.id = cls_id) THEN
                      f_result := 0;
                      RAISE EXCEPTION 'Класса с ID=% не существует!', cls_id;
                      RETURN f_result;
                    END IF;
                    IF NOT EXISTS(SELECT * FROM parametr_parametr WHERE parametr_parametr.id = parametr_id) THEN
                      f_result := 0;
                      RAISE EXCEPTION 'Параметра с ID=% не существует!', parametr_id;
                      RETURN f_result;
                    END IF;
                    product_classes_parent_node_id := 1;
                    SELECT class_id FROM find_gr_Gr(product_classes_parent_node_id) INTO cls_ids;
                    -- IF NOT EXISTS(SELECT class_id FROM find_gr_gr(product_classes_parent_node_id) WHERE products_prod.class_field_id=cls_id) THEN
                      -- RAISE EXCEPTION 'Элемент с ID=% не является изделием!', cls_id;
                    -- END IF;
                    IF NOT EXISTS(SELECT * FROM products_prod WHERE products_prod.class_field_id = cls) THEN
                        RAISE EXCEPTION 'Элемент с ID=% не является изделием!', cls_id;
                    END IF;
                    SELECT * INTO parametr_record FROM parametr_parametr WHERE 
                    parametr.id = parametr_id;
                    parametr_tp := parametr_record.parametr_type_id;
                    IF EXISTS(SELECT class_id FROM find_gr_gr(enum_parent_node_id) WHERE products_prod.class_id = parametr_tp) THEN
                      IF min_val != 0.0 OR max_val != 0.0 THEN
                        f_result := 0;
                        RAISE EXCEPTION 'Нельзя присваивать параметру-перечислению значения MIN_VALUE и MAX_VALUE!';
                        RETURN f_result;
                      END IF;
                      f_result := 1;
                      INSERT INTO classes_parclass VALUES(cls_id, parametr_id, NULL, NULL);
                      RETURN f_result;
                    ELSE
                      f_result := 1;
                      INSERT INTO classes_parclass VALUES(cls_id, parametr_id, min_val, max_val);
                      RETURN f_result;
                    END IF;
                  END;
                $$;
            """,
            reverse_sql="DROP FUNCTION to_add_parametr_to_class(integer, integer, double precision, double precision);",
        ),
    ]
