# Generated by Django 4.2 on 2026-06-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parametr", "0003_alter_parametr_short_name"),
        ("ei", "0004_alter_ei_code"),
        ("classes", "0006_add_my_functions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classstruct",
            name="base_ei",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ei.ei",
                verbose_name="Базовая единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="classstruct",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=16,
                verbose_name="Сокращенное название класса",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parclass",
            name="class_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_params",
                to="classes.classstruct",
                verbose_name="Класс",
            ),
        ),
        migrations.AlterField(
            model_name="parclass",
            name="max_value",
            field=models.FloatField(
                blank=True, default=0.0, verbose_name="Максимальное значение параметра"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parclass",
            name="min_value",
            field=models.FloatField(
                blank=True, default=0.0, verbose_name="Минимальное значение параметра"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parclass",
            name="parametr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="parametr.parametr",
                verbose_name="Параметр",
            ),
        ),
    ]
