# Generated by Django 4.2 on 2026-06-29 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0007_alter_classstruct_base_ei_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parclass",
            name="num",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Позиция в списке параметров класса",
            ),
        ),
        migrations.AddConstraint(
            model_name="parclass",
            constraint=models.CheckConstraint(
                check=models.Q(("num__gt", 0)), name="parclass_num_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="parclass",
            constraint=models.CheckConstraint(
                check=models.Q(("max_value__gte", models.F("min_value"))),
                name="parclass_max_gte_min",
            ),
        ),
    ]
