# Generated by Django 4.2 on 2026-06-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0008_alter_parclass_num_parclass_parclass_num_gt_zero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parclass",
            name="max_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Максимальное значение параметра"
            ),
        ),
        migrations.AlterField(
            model_name="parclass",
            name="min_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Минимальное значение параметра"
            ),
        ),
    ]
