# Generated by Django 4.2 on 2026-07-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0010_alter_parclass_max_value_alter_parclass_min_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parclass",
            name="max_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Максимальное значение параметра"
            ),
        ),
        migrations.AlterField(
            model_name="parclass",
            name="min_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Минимальное значение параметра"
            ),
        ),
    ]
