# Generated by Django 5.2 on 2026-09-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0011_alter_parclass_max_value_alter_parclass_min_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classstruct",
            options={
                "permissions": [
                    (
                        "keep_account_of_means_of_labor",
                        "Может вести учет средства труда",
                    )
                ],
                "verbose_name": "Классификатор",
                "verbose_name_plural": "Классификатор",
            },
        ),
    ]
