# Generated by Django 5.2 on 2026-09-23 10:21

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0012_alter_classstruct_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.DROP_CHECK_CLASSIFICATOR_CYCLE_OLD,
            reverse_sql=DatabaseFunctions.CHECK_CLASSIFICATOR_CYCLE_OLD,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_CLASSIFICATOR_CYCLE,
            reverse_sql=DatabaseFunctions.DROP_CHECK_CLASSIFICATOR_CYCLE,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_CLASSIFICATOR_CYCLE_WRAPPER_FUNCTION,
            reverse_sql=DatabaseFunctions.DROP_CHECK_CLASSIFICATOR_WRAPPER_FUNCTION,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_CLASSIFICATOR_CYCLE_TRIGGER,
            reverse_sql=DatabaseFunctions.DROP_CHECK_CLASSFICATOR_CYCLE_TRIGGER,
        ),
    ]
