# Generated by Django 5.2 on 2026-09-29 11:12

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0013_alter_check_classificator_cycle_sql_function"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.DROP_DELETE_CLASS_AND_DESCENDANTS,
            reverse_sql=DatabaseFunctions.DELETE_CLASS_AND_DESCENDANTS
        ),
    ]
