PARAMETR_NAME_MAX_LENGTH = 64
PARAMETR_SHORT_NAME_MAX_LENGTH = 16
PARAMETR_FORM_NAME_MAX_LENGTH = 75
AGR_INLINE_EXTRA = 1
AGREGAT_TYPE_ID = 30
FASTENER_ID = 2
STRING_ENUMS_ID = 15
IMAGE_ENUMS_ID = 16
