ENUMS_NAME_MAX_LENGTH = 128
ENUMS_SHORT_NAME_MAX_LENGTH = 32
STRING_ENUMS_ID = 15
IMAGE_ENUMS_ID = 16
DOUBLE_ENUMS_ID = 18
INT_ENUMS_ID = 19
FASTENER_ID = 2
ENUMS_FORM_NAME_MAX_LENGTH = 75
ENUMS_FORM_SHORT_NAME_MAX_LENGTH = 15
ENUMS_FORM_INT_VALUE_LOWER_BOUND = 0
ENUMS_FORM_DOUBLE_VALUE_LOWER_BOUND = 0.0

MAX_NUM_VALUE = 32767
