# Generated by Django 4.2 on 2025-06-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enums", "0001_initial"),
        ("products", "0002_parprod_parprod_parprod_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parprod",
            name="enum_val",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enums.enums",
                verbose_name="Значение перечисления параметра",
            ),
        ),
    ]
