# Generated by Django 4.2 on 2026-06-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enums", "0004_alter_enums_enum_alter_enums_image"),
        ("classes", "0007_alter_classstruct_base_ei_and_more"),
        ("products", "0005_alter_prod_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parprod",
            name="double_value",
            field=models.FloatField(
                null=True, verbose_name="Вещественное значение параметра"
            ),
        ),
        migrations.AlterField(
            model_name="parprod",
            name="enum_val",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enums.enums",
                verbose_name="Значение перечисления параметра",
            ),
        ),
        migrations.AlterField(
            model_name="parprod",
            name="int_value",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Целочисленное значение параметра"
            ),
        ),
        migrations.AlterField(
            model_name="parprod",
            name="prod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_params",
                to="products.prod",
                verbose_name="Изделие",
            ),
        ),
        migrations.AlterField(
            model_name="prod",
            name="class_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_products",
                to="classes.classstruct",
                verbose_name="Родительский класс",
            ),
        ),
        migrations.AlterField(
            model_name="prod",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=16,
                verbose_name="Сокращенное название изделия",
            ),
            preserve_default=False,
        ),
    ]
