# Generated by Django 4.2 on 2026-06-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enums", "0006_alter_enums_image_alter_enums_name_and_more"),
        ("products", "0006_alter_parprod_double_value_alter_parprod_enum_val_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parprod",
            name="double_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Вещественное значение параметра"
            ),
        ),
        migrations.AlterField(
            model_name="parprod",
            name="enum_val",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enums.enums",
                verbose_name="Значение перечисления параметра",
            ),
        ),
        migrations.AlterField(
            model_name="parprod",
            name="int_value",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Целочисленное значение параметра"
            ),
        ),
    ]
