# Generated by Django 5.2 on 2026-08-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_parprod_double_value_alter_parprod_enum_val_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prod",
            name="cost",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Стоимость изделия"
            ),
        ),
        migrations.AddField(
            model_name="prod",
            name="modification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.prod",
            ),
        ),
    ]
