# Generated by Django 5.2 on 2026-08-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0004_alter_ei_code"),
        ("products", "0008_prod_cost_prod_modification"),
    ]

    operations = [
        migrations.AddField(
            model_name="prod",
            name="ei",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="ei.ei"
            ),
        ),
    ]
