# Generated by Django 5.2 on 2026-09-03 12:34

import products.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_prod_ei"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prod",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=products.constants.ProdConsts["DECIMAL_PLACES"],
                max_digits=products.constants.ProdConsts["MAX_DIGITS"],
                null=True,
                verbose_name="Стоимость изделия",
            ),
        ),
    ]
