# Generated by Django 5.2 on 2026-09-03 13:13

import django.core.validators
import products.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_prod_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prod",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=products.constants.ProdConsts["DECIMAL_PLACES"],
                max_digits=products.constants.ProdConsts["MAX_DIGITS"],
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        products.constants.ProdConsts["MIN_COST"]
                    )
                ],
                verbose_name="Стоимость изделия",
            ),
        ),
    ]
