# Generated by Django 5.2 on 2026-09-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0004_alter_ei_code"),
        ("products", "0011_alter_prod_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prod",
            name="ei",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ei.ei",
                verbose_name="Единица измерения изделия",
            ),
        ),
        migrations.AlterField(
            model_name="prod",
            name="modification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.prod",
                verbose_name="Базовое изделие",
            ),
        ),
    ]
