# Generated by Django 5.2 on 2026-09-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_prod_ei_alter_prod_modification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prod",
            options={
                "permissions": [
                    ("can_create_modification", "Может создавать модификации изделий")
                ],
                "verbose_name": "Изделие",
                "verbose_name_plural": "Изделия",
            },
        ),
    ]
