# Generated by Django 5.2 on 2026-09-25 11:04

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_prod_options"),
        ("specifications", "0009_alter_prodcomponent_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.RECALCULATE_PRODUCT_PRICE_AFTER_PRICE_UPDATING_FUNCTION,
            reverse_sql=DatabaseFunctions.DROP_PRICE_RECALCULATION_FUNCTION,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.RECALCULATE_PRODUCT_PRICE_AFTER_PRICE_UPDATING_TRIGGER,
            reverse_sql=DatabaseFunctions.DROP_PRICE_RECALCULATION_TRIGGER,
        ),
    ]
