# Generated by Django 5.2 on 2026-09-25 13:13

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_create_prod_price_recalculation_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.RECALCULATE_PRODUCT_PRICE_DUE_TO_QUANTITY_UPDATE_FUNCTION,
            reverse_sql=DatabaseFunctions.DROP_PRICE_RECALCULATION_DUE_TO_QUANTITY_UPDATE_FUNCTION,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.RECALCULATE_PRODUCT_PRICE_DUE_TO_QUANTITY_UPDATE_TRIGGER,
            reverse_sql=DatabaseFunctions.DROP_PRICE_RECALCULATION_DUE_TO_QUANTITY_UPDATE_TRIGGER,
        )
    ]
