# Generated by Django 4.2 on 2025-06-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_alter_classstruct_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(verbose_name='Номер позиции в перечислении')),
                ('name', models.CharField(max_length=128, verbose_name='Название перечисления')),
                ('short_name', models.CharField(max_length=32, verbose_name='Сокращенное название перечисления')),
                ('double_value', models.FloatField(blank=True, null=True, verbose_name='Вещественное значение перечисления')),
                ('int_value', models.IntegerField(blank=True, null=True, verbose_name='Целочисленное значение перечисления')),
                ('image_value', models.ImageField(upload_to='enum_images/', verbose_name='Изображение перечисления')),
                ('enum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classstruct', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name': 'Значение перечисления',
                'verbose_name_plural': 'Значения перечисления',
            },
        ),
    ]
