# Generated by Django 4.2 on 2025-06-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enums", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enums",
            old_name="image_value",
            new_name="image",
        ),
    ]
