# Generated by Django 4.2 on 2026-06-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0007_alter_classstruct_base_ei_and_more"),
        ("enums", "0003_alter_enums_name_alter_enums_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enums",
            name="enum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enum_values",
                to="classes.classstruct",
                verbose_name="Родительский класс",
            ),
        ),
        migrations.AlterField(
            model_name="enums",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="enum_images/",
                verbose_name="Изображение перечисления",
            ),
        ),
    ]
