# Generated by Django 4.2 on 2026-06-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0007_alter_classstruct_base_ei_and_more"),
        ("enums", "0004_alter_enums_enum_alter_enums_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enums",
            unique_together={("enum", "num")},
        ),
    ]
