# Generated by Django 4.2 on 2026-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enums", "0005_alter_enums_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enums",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="enum_images/",
                verbose_name="Изображение перечисления",
            ),
        ),
        migrations.AlterField(
            model_name="enums",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Название перечисления",
            ),
        ),
        migrations.AlterField(
            model_name="enums",
            name="short_name",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Сокращенное название перечисления",
            ),
        ),
    ]
