# Generated by Django 5.2 on 2026-09-02 07:20

import django.db.models.deletion
import route_tech.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0011_alter_parclass_max_value_alter_parclass_min_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomicActivitySubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=route_tech.constants.EASConsts["NAME_MAX_LENGTH"],
                        verbose_name="Название субъекта экономической деятельности",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=route_tech.constants.EASConsts[
                            "SHORT_NAME_MAX_LENGTH"
                        ],
                        verbose_name="Сокращенное название субъекта экономической деятельности",
                    ),
                ),
                (
                    "main_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects_by_class",
                        to="classes.classstruct",
                        verbose_name="Ссылка на класс субъекта экономической деятельности",
                    ),
                ),
                (
                    "main_subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="route_tech.economicactivitysubject",
                        verbose_name="Родительский субъект экономической деятельности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Субъект экономической деятельности",
                "verbose_name_plural": "Субъекты экономической деятельности",
            },
        ),
    ]
