# Generated by Django 5.2 on 2026-09-02 08:26

import django.db.models.deletion
import route_tech.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0011_alter_parclass_max_value_alter_parclass_min_value"),
        ("route_tech", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupWorkingCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=route_tech.constants.GWCConsts["NAME_MAX_LENGTH"],
                        verbose_name="Название группового рабочего центра",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=route_tech.constants.GWCConsts[
                            "SHORT_NAME_MAX_LENGTH"
                        ],
                        verbose_name="Сокращенное название группового рабочего центра",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Количество рабочих мест на групповом рабочим центре"
                    ),
                ),
                (
                    "eas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_centers_by_subject",
                        to="route_tech.economicactivitysubject",
                        verbose_name="Ссылка на субъект экономической деятельности",
                    ),
                ),
                (
                    "main_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_centers_by_class",
                        to="classes.classstruct",
                        verbose_name="Ссылка на родительский класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Групповой рабочий центр",
                "verbose_name_plural": "Групповые рабочие центры",
            },
        ),
    ]
