# Generated by Django 5.2 on 2026-09-02 09:29

import django.db.models.deletion
import route_tech.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0011_alter_parclass_max_value_alter_parclass_min_value"),
        ("enums", "0006_alter_enums_image_alter_enums_name_and_more"),
        ("products", "0009_prod_ei"),
        ("route_tech", "0002_groupworkingcenter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_of_workers",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        verbose_name="Количество исполнителей, занятых при выполнении операции",
                    ),
                ),
                (
                    "t_pz",
                    models.FloatField(
                        default=route_tech.constants.ProdOperConsts["T_PZ_DEFAULT"],
                        verbose_name="Норма подготовительно-заключительного времени на операцию",
                    ),
                ),
                (
                    "t_sht",
                    models.FloatField(
                        default=route_tech.constants.ProdOperConsts["T_PZ_DEFAULT"],
                        verbose_name="Норма штучного времени на операцию",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="center_operations",
                        to="route_tech.groupworkingcenter",
                        verbose_name="Групповой рабочий центр",
                    ),
                ),
                (
                    "prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prod_operations",
                        to="products.prod",
                        verbose_name="Изделие",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profession_operations",
                        to="classes.classstruct",
                        verbose_name="Профессия рабочего",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualification_operations",
                        to="enums.enums",
                        verbose_name="Квалификация рабочего",
                    ),
                ),
                (
                    "tech_oper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_operations",
                        to="classes.classstruct",
                        verbose_name="Операция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пара класса <Изделие-операция>",
                "verbose_name_plural": "Пары класса <Изделие-операция>",
            },
        ),
    ]
