# Generated by Django 5.2 on 2026-09-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0011_alter_parclass_max_value_alter_parclass_min_value"),
        ("route_tech", "0003_prodoperation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodoperation",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualification_operations",
                to="classes.classstruct",
                verbose_name="Квалификация рабочего",
            ),
        ),
    ]
