# Generated by Django 5.2 on 2026-09-02 12:41

import django.core.validators
import django.db.models.deletion
import route_tech.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_tech", "0004_alter_prodoperation_qualification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdOperationPos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_quantity",
                    models.DecimalField(
                        decimal_places=route_tech.constants.ProdOperationPosConsts[
                            "DECIMAL_PLACES"
                        ],
                        max_digits=route_tech.constants.ProdOperationPosConsts[
                            "MAX_DIGITS"
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(
                                route_tech.constants.ProdOperationPosConsts["MIN_VALUE"]
                            )
                        ],
                        verbose_name="Расход входного ресурса",
                    ),
                ),
                (
                    "output_quantity",
                    models.DecimalField(
                        decimal_places=route_tech.constants.ProdOperationPosConsts[
                            "DECIMAL_PLACES"
                        ],
                        max_digits=route_tech.constants.ProdOperationPosConsts[
                            "MAX_DIGITS"
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(
                                route_tech.constants.ProdOperationPosConsts["MIN_VALUE"]
                            )
                        ],
                        verbose_name="Количество выходного ресурса",
                    ),
                ),
                (
                    "input_prod_oper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_prod_oper_positions",
                        to="route_tech.prodoperation",
                        verbose_name="Входная пара <Изделие-операция>",
                    ),
                ),
                (
                    "output_prod_oper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_prod_oper_positions",
                        to="route_tech.prodoperation",
                        verbose_name="Выходная пара <Изделие-операция>",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция входного ресурса",
                "verbose_name_plural": "Позиции входных ресурсов",
            },
        ),
    ]
