# Generated by Django 5.2 on 2026-09-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_tech", "0005_prodoperationpos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="economicactivitysubject",
            name="main_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="route_tech.economicactivitysubject",
                verbose_name="Родительский субъект экономической деятельности",
            ),
        ),
        migrations.AlterField(
            model_name="groupworkingcenter",
            name="place",
            field=models.PositiveSmallIntegerField(
                verbose_name="Количество рабочих мест на групповом рабочем центре"
            ),
        ),
    ]
