# Generated by Django 5.2 on 2026-09-23 18:04

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("route_tech", "0006_alter_economicactivitysubject_main_subject_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_EAS_CYCLE,
            reverse_sql=DatabaseFunctions.DROP_CHECK_EAS_CYCLE,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_EAS_CYCLE_WRAPPER_FUNCTION,
            reverse_sql=DatabaseFunctions.DROP_CHECK_EAS_CYCLE_WRAPPER_FUNCTION,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_EAS_CYCLE_TRIGGER,
            reverse_sql=DatabaseFunctions.DROP_CHECK_EAS_CYCLE_TRIGGER,
        ),
    ]
