# Generated by Django 5.2 on 2026-09-26 12:02

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("route_tech", "0007_create_trigger_checking_cycle"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.LOG_PRODCOMPONENT_CHANGE_FUNCTION,
            reverse_sql=DatabaseFunctions.DROP_LOG_PRODCOMPONENT_CHANGE_FUNCTION,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.LOG_PRODCOMPONENT_CHANGE_TRIGGER,
            reverse_sql=DatabaseFunctions.DROP_LOG_PRODCOMPONENT_CHANGE_TRIGGER,
        ),
    ]
