# Generated by Django 5.2 on 2026-10-01 08:34

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("route_tech", "0008_create_prodcomponent_change_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.CREATE_DESCENDANT_RECORD_TYPE,
            reverse_sql=DatabaseFunctions.DROP_DESCENDANT_RECORD_TYPE,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.GET_ALL_EAS_DESCENDANTS,
            reverse_sql=DatabaseFunctions.DROP_GET_ALL_EAS_DESCENDANTS,
        )
    ]
