# Generated by Django 5.2 on 2026-10-01 11:12

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("route_tech", "0009_create_get_all_eas_descendants"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.CREATE_TECH_ROUTE_TYPE,
            reverse_sql=DatabaseFunctions.DROP_TECH_ROUTE_TYPE,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.CREATE_TECH_ROUTE_FUNCTION,
            reverse_sql=DatabaseFunctions.DROP_TECH_ROUTE_FUNCTION,
        ),
    ]
