# Generated by Django 4.2 on 2026-06-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parametr", "0003_alter_parametr_short_name"),
        ("agregat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agregat",
            name="agr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agregat_parametrs",
                to="parametr.parametr",
                verbose_name="Агрегат",
            ),
        ),
        migrations.AlterField(
            model_name="agregat",
            name="par",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="parametr.parametr",
                verbose_name="Параметр",
            ),
        ),
    ]
