CLASS_STRUCT_NAME_MAX_LENGTH = 128
CLASS_STRUCT_SHORT_NAME_MAX_LENGTH = 16
PARCLASS_INLINE_EXTRA = 1
PARCLASS_NUM_MIN_VALUE = 1
ENUM_CLASSES_IDS = [15, 16, 18, 19]
ENUM_PARENT_NODE_ID = 14
NUM_PARAM_ID = 26
PRODUCT_ID = 1
NUM_ENUM_ID = 17
PROD_CLASS_FORM_MAX_LENGTH = 128
PROD_CLASS_FORM_SHORT_NAME_MAX_LENGTH = 16
ENUM_CLASS_FORM_NAME_MAX_LENGTH = 75

PARCLASS_FORM_MIN_VALUE_LOWER_BOUND = 0.0
PARCLASS_FORM_MAX_VALUE_LOWER_BOUND = 0.0

FASTENER_ID = 2
NUTS_ID = 5
