# Generated by Django 4.2 on 2026-06-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ei",
            name="convert_factor",
            field=models.FloatField(
                null=True, verbose_name="Множитель единицы измерения"
            ),
        ),
        migrations.AlterField(
            model_name="ei",
            name="main_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ei.ei",
                verbose_name="Родительский класс единицы измерения",
            ),
        ),
    ]
