# Generated by Django 4.2 on 2026-06-28 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0002_alter_ei_convert_factor_alter_ei_main_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ei",
            name="main_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="child_eis",
                to="ei.ei",
                verbose_name="Родительский класс единицы измерения",
            ),
        ),
    ]
