# Generated by Django 4.2 on 2026-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0003_alter_ei_main_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ei",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=5,
                verbose_name="Код единицы измерения",
            ),
            preserve_default=False,
        ),
    ]
