# Generated by Django 5.2 on 2026-09-03 13:43

import ei.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0004_alter_ei_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ei",
            name="convert_factor",
            field=models.DecimalField(
                decimal_places=ei.constants.EiConsts["DECIMAL_PLACES"],
                max_digits=ei.constants.EiConsts["MAX_DIGITS"],
                null=True,
                verbose_name="Множитель единицы измерения",
            ),
        ),
    ]
