# Generated by Django 5.2 on 2026-09-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0005_alter_ei_convert_factor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ei",
            name="convert_factor",
            field=models.FloatField(
                null=True, verbose_name="Множитель единицы измерения"
            ),
        ),
    ]
