# Generated by Django 5.2 on 2026-09-23 15:32

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0006_alter_ei_convert_factor"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_EI_CYCLE,
            reverse_sql=DatabaseFunctions.DROP_CHECK_EI_CYCLE,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_EI_CYCLE_WRAPPER_FUNCTION,
            reverse_sql=DatabaseFunctions.DROP_CHECK_EI_CYLCE_FUNCTION,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.CHECK_EI_CYCLE_TRIGGER,
            reverse_sql=DatabaseFunctions.DROP_EI_CYCLE_TRIGGER,
        ),
    ]
