# Generated by Django 5.2 on 2026-09-29 09:12

import ei.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0007_create_trigger_checking_cycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ei",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=ei.constants.EiConsts["NAME_MAX_LENGTH"],
                verbose_name="Название единицы измерения",
            ),
        ),
    ]
