# Generated by Django 5.2 on 2026-09-29 09:50

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("ei", "0008_alter_ei_name"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.EI_MAIN_CLASS_DELETE_FUNCTION,
            reverse_sql=DatabaseFunctions.DROP_EI_MAIN_CLASS_DELETE_FUNCTION,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.EI_MAIN_CLASS_DELETE_TRIGGER,
            reverse_sql=DatabaseFunctions.DROP_EI_MAIN_CLASS_DELETE_TRIGGER,
        )
    ]
