# Generated by Django 5.2 on 2026-09-11 18:34

import accounts.constants
import accounts.errors
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Идентификатор")),
                (
                    "name",
                    models.CharField(
                        max_length=accounts.constants.RoleConsts["NAME_MAX_LENGTH"],
                        unique=True,
                        verbose_name="Название роли",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание роли"),
                ),
                (
                    "is_self_registerable",
                    models.BooleanField(
                        default=True, verbose_name="Является ли роль саморегистрируемой"
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role",
                        to="auth.group",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=accounts.constants.UserConsts[
                            "FIRST_NAME_MAX_LENGTH"
                        ],
                        unique=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=accounts.constants.UserConsts[
                            "FIRST_NAME_MAX_LENGTH"
                        ],
                        verbose_name="Имя",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=accounts.constants.UserConsts[
                            "FIRST_NAME_MAX_LENGTH"
                        ],
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=accounts.constants.UserConsts[
                            "FIRST_NAME_MAX_LENGTH"
                        ],
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=accounts.constants.UserConsts[
                            "PHONE_NUMBER_MAX_LENGTH"
                        ],
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code=accounts.errors.UserErrors["INVALID_PHONE_NUMBER"],
                                message="Введите номер телефона в формате +7 (ХХХ) ХХХ-ХХ-ХХ",
                                regex="^\\+7 \\(\\d{3}\\) \\d{3}\\-\\d{2}-\\d{2}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата и время регистрации",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Сотрудник"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.role",
                        verbose_name="Роль пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ("last_name", "first_name"),
            },
        ),
    ]
