# Generated by Django 5.2 on 2026-09-11 11:35

import accounts.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Идентификатор")),
                (
                    "name",
                    models.CharField(
                        max_length=accounts.constants.RoleConsts["NAME_MAX_LENGTH"],
                        verbose_name="Название роли",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание роли"),
                ),
                (
                    "is_self_registerable",
                    models.BooleanField(
                        default=True, verbose_name="Является ли роль саморегистрируемой"
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role",
                        to="auth.group",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
