# Generated by Django 5.2 on 2026-09-11 11:38

from django.db import migrations


ROLES = [
    (
        "handbook-executive", 
        "Ответственный за справочник", 
        "Отвечает за ведение классификатора, ведение справочника параметров, работу с перечислениями",
        False
    ), 
    (
        "handbook-user", 
        "Пользователь справочника", 
        "Отвечает за работу со значениями перечислений, поиск подклассов заданного класса, поиск всех родителей класса, изменение порядка класса в списке подклассов", 
        False
    ),
    (
        "builder", 
        "Конструктор", 
        "Отвечает за ведение справочника изделий, создание модификаций, управление изменениями, расчет сводных норм расхода материальных ресурсов, редактирование спецификаций", 
        False
    ),
    (
        "technologist", 
        "Технолог", 
        "Отвечает за поиск подклассов заданного класса, работу со значениями перечислений, спецификацию ГРЦ, подготовку маршрутной технологии, спецификацию моделей средств труда", 
        False
    ),
    (
        "chief-mechanic-dept-employee",
        "Сотрудник отдела главного механика",
        "Отвечает за спецификацию моделей средств труда, учет средств труда",
        False
    ),
    (
        "sales-dept-employee", 
        "Сотрудника отдела сбыта", 
        "Отвечает за регистрацию заявки, формирование позиций заказа, согласование позиций заказа, расчет стоимости позиции, редактирование количества, задание варианта исполнения", 
        False
    ),
    (
        "production-dept-employee", 
        "Сотрудник производственного отдела", 
        "Отвечает за согласование заказа и позиций", 
        False
    ),
    (
        "client", 
        "Заказчик", 
        "Отвечает за подачу заявки и согласование заказа", 
        False
    ),
    (
        "economic-planning-dept-employee", 
        "Сотрудник планово-экономического отдела", 
        "Отвечает за расчет стоимости заказа и позиций", 
        False
    ),
]


def create_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Role = apps.get_model("accounts", "Role")

    for code, name, description, self_reg in ROLES:
        group, _ = Group.objects.get_or_create(name=name)
        Role.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "description": description,
                "group": group,
                "is_self_registerable": self_reg,
            },
        )


def delete_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Role = apps.get_model("accounts", "Role")

    codes = [r[0] for r in ROLES]
    names = [r[1] for r in ROLES]
    Role.objects.filter(code__in=codes).delete()
    Group.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=create_roles,
            reverse_code=delete_roles,
        )
    ]
