# Generated by Django 5.2 on 2026-09-11 12:47

from django.db import migrations
from django.db.models import Model

def assign_permissions(apps, schema_editor):
    Group: Model = apps.get_model("auth", "Group")
    Permission: Model = apps.get_model("auth", "Permission")

    handbook_executives = (
        Group.objects
        .filter(role__code="handbook-executive")
        .first()
    )

    ei_permissions = Permission.objects.filter(
        content_type__app_label="ei",
        codename__in=[
            "add_ei",
            "change_ei",
            "delete_ei",
            "view_ei",
        ]
    )

    classes_permissions = Permission.objects.filter(
        content_type__app_label="classes",
        codename__in=[
            "add_classstruct",
            "change_classstruct",
            "delete_classstruct",
            "view_classstruct",
        ]
    )

    parclass_permissions = Permission.objects.filter(
        content_type__app_label="classes",
        codename__in=[
            "add_parclass",
            "change_parclass",
            "delete_parclass",
            "view_parclass",
        ]
    )

    enums_permissions = Permission.objects.filter(
        content_type__app_label="enums",
        codename__in=[
            "add_enums",
            "change_enums",
            "delete_enums",
            "view_enums",
        ]
    )

    parprod_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "add_parprod",
            "change_parprod",
            "delete_parprod",
            "view_parprod",
        ]
    )

    prod_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "add_prod",
            "change_prod",
            "delete_prod",
            "view_prod",
        ]
    )

    parametr_permissions = Permission.objects.filter(
        content_type__app_label="parametr",
        codename__in=[
            "add_parametr",
            "change_parametr",
            "delete_parametr",
            "view_parametr",
        ]
    )

    agregat_permissions = Permission.objects.filter(
        content_type__app_label="agregat",
        codename__in=[
            "add_agregat",
            "change_agregat",
            "delete_agregat",
            "view_agregat",
        ]
    )

    all_permissions = [
        *ei_permissions, *classes_permissions, *parclass_permissions,
        *enums_permissions, *prod_permissions, *parprod_permissions,
        *parametr_permissions, *agregat_permissions,
    ]

    handbook_executives.permissions.add(*all_permissions)

    # присваиваем права группе пользователей справочника
    handbook_users = (
        Group.objects
        .filter(role__code="handbook-user")
        .first()
    )

    # разрешения на просмотр моделей ClassStruct, ParClass, Ei, Prod, ParProd, Enums, Parametr
    handbook_permissions = Permission.objects.filter(
        codename__in=[
            "view_ei",
            "view_enums",
            "view_parametr",
            "view_parclass",
            "view_parprod",
            "view_prod",
            "view_classstruct",
            "view_agregat",
        ]
    )

    handbook_users.permissions.add(*handbook_permissions)

    # присваиваем права группе конструкторов
    builders = (
        Group.objects
        .filter(role__code="builder")
        .first()
    )

    builders_specifications_permissions = Permission.objects.filter(
        content_type__app_label="specifications",
        codename__in=[
            "can_get_total_cost_ratio",
            "can_get_product_changelog",
            "can_edit_specification",
        ]
    )

    builders_products_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "can_create_modification"
        ]
    )

    builders.permissions.add(*builders_specifications_permissions)
    builders.permissions.add(*builders_products_permissions)

    # присваиваем права группе технологов
    technologists = (
        Group.objects
        .filter(role__code="technologist")
        .first()
    )

    technologists_permissions = Permission.objects.filter(
        codename__in=[
            "add_economicactivitysubject",
            "change_economicactivitysubject",
            "delete_economicactivitysubject",
            "view_economicactivitysubject",
            "add_groupworkingcenter",
            "change_groupworkingcenter",
            "delete_groupworkingcenter",
            "view_groupworkingcenter",
            "add_prodoperation",
            "change_prodoperation",
            "delete_prodoperation",
            "view_prodoperation",
            "add_prodoperationpos",
            "change_prodoperationpos",
            "delete_prodoperationpos",
            "view_prodoperationpos",
            "add_enums",
            "change_enums",
            "delete_enums",
            "view_enums",
        ]
    )

    technologists.permissions.add(*technologists_permissions)

    # присваиваем права группе сотрудников отдела главного механика
    chief_mechanic_dept_employees = (
        Group.objects
        .filter(role__code="chief-mechanic-dept-employee")
        .first()
    )

    chief_mechanic_dept_permissions = Permission.objects.filter(
        codename__in=[
            "keep_account_of_means_of_labor",
        ]
    )

    chief_mechanic_dept_employees.permissions.add(*chief_mechanic_dept_permissions)


def remove_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    handbook_executives = (
        Group.objects
        .filter(role__code="handbook-executive")
        .first()
    )

    ei_permissions = Permission.objects.filter(
        content_type__app_label="ei",
        codename__in=[
            "add_ei",
            "change_ei",
            "delete_ei",
            "view_ei",
        ]
    )

    classes_permissions = Permission.objects.filter(
        content_type__app_label="classes",
        codename__in=[
            "add_classstruct",
            "change_classstruct",
            "delete_classstruct",
            "view_classstruct",
        ]
    )

    parclass_permissions = Permission.objects.filter(
        content_type__app_label="classes",
        codename__in=[
            "add_parclass",
            "change_parclass",
            "delete_parclass",
            "view_parclass",
        ]
    )

    enums_permissions = Permission.objects.filter(
        content_type__app_label="enums",
        codename__in=[
            "add_enums",
            "change_enums",
            "delete_enums",
            "view_enums",
        ]
    )

    parprod_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "add_parprod",
            "change_parprod",
            "delete_parprod",
            "view_parprod",
        ]
    )

    prod_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "add_prod",
            "change_prod",
            "delete_prod",
            "view_prod",
        ]
    )

    parametr_permissions = Permission.objects.filter(
        content_type__app_label="parametr",
        codename__in=[
            "add_parametr",
            "change_parametr",
            "delete_parametr",
            "view_parametr",
        ]
    )

    agregat_permissions = Permission.objects.filter(
        content_type__app_label="agregat",
        codename__in=[
            "add_agregat",
            "change_agregat",
            "delete_agregat",
            "view_agregat",
        ]
    )

    handbook_executives.permissions.remove(*ei_permissions)
    handbook_executives.permissions.remove(*parclass_permissions)
    handbook_executives.permissions.remove(*parametr_permissions)
    handbook_executives.permissions.remove(*classes_permissions)
    handbook_executives.permissions.remove(*parprod_permissions)
    handbook_executives.permissions.remove(*prod_permissions)
    handbook_executives.permissions.remove(*enums_permissions)
    handbook_executives.permissions.remove(*agregat_permissions)

    handbook_users = (
        Group.objects
        .filter(role__code="handbook-user")
        .first()
    )

    # разрешения на просмотр моделей ClassStruct, ParClass, Ei, Prod, ParProd, Enums, Parametr
    handbook_permissions = Permission.objects.filter(
        codename__in=[
            "view_ei",
            "view_enums",
            "view_parametr",
            "view_parclass",
            "view_parprod",
            "view_prod",
            "view_classstruct",
            "view_agregat",
        ]
    )

    handbook_users.permissions.remove(*handbook_permissions)

    builders = (
        Group.objects
        .filter(role__code="builder")
        .first()
    )

    builders_parametr_permissions = Permission.objects.filter(
        content_type__app_label="specifications",
        codename__in=[
            "can_get_total_cost_ratio",
            "can_get_product_changelog",
            "can_edit_specification",
        ]
    )

    builders_products_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "can_create_modification"
        ]
    )

    builders.permissions.remove(*builders_products_permissions)
    builders.permissions.remove(*builders_parametr_permissions)

    technologists = (
        Group.objects
        .filter(role__code="technologist")
        .first()
    )

    technologists_permissions = Permission.objects.filter(
        codename__in=[
            "add_economicactivitysubject",
            "change_economicactivitysubject",
            "delete_economicactivitysubject",
            "view_economicactivitysubject",
            "add_groupworkingcenter",
            "change_groupworkingcenter",
            "delete_groupworkingcenter",
            "view_groupworkingcenter",
            "add_prodoperation",
            "change_prodoperation",
            "delete_prodoperation",
            "view_prodoperation",
            "add_prodoperationpos",
            "change_prodoperationpos",
            "delete_prodoperationpos",
            "view_prodoperationpos",
            "add_enums",
            "change_enums",
            "delete_enums",
            "view_enums",
        ]
    )

    technologists.permissions.remove(*technologists_permissions)

    chief_mechanic_dept_employees = (
        Group.objects
        .filter(role__code="chief-mechanic-dept-employee")
        .first()
    )

    chief_mechanic_dept_permissions = Permission.objects.filter(
        codename__in=[
            "keep_account_of_means_of_labor",
        ]
    )

    chief_mechanic_dept_employees.permissions.remove(*chief_mechanic_dept_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_create_roles"),
        ("agregat", "0002_alter_agregat_agr_alter_agregat_par"),
        ("classes", "0012_alter_classstruct_options"),
        ("ei", "0006_alter_ei_convert_factor"),
        ("enums", "0006_alter_enums_image_alter_enums_name_and_more"),
        ("parametr", "0005_alter_parametr_short_name"),
        ("products", "0013_alter_prod_options"),
        ("specifications", "0009_alter_prodcomponent_options"),
    ]

    operations = [
        migrations.RunPython(
            code=assign_permissions,
            reverse_code=remove_permissions,
        )
    ]
