# Generated by Django 5.2 on 2026-09-11 12:47

from django.db import migrations
from django.db.models import Model
from django.contrib.auth.models import Group as Grp

def assign_permissions(apps, schema_editor):
    Group: Model = apps.get_model("auth", "Group")
    Permission: Model = apps.get_model("auth", "Permission")

    # присваиваем права группе ответственных за справочник
    handbook_executives: Grp = (
        Group.objects
        .filter(role__code="handbook-executive")
        .first()
    )

    ei_permissions = Permission.objects.filter(
        content_type__app_label="ei",
        codename__in=[
            "add_ei",
            "change_ei",
            "delete_ei",
            "view_ei",
        ]
    )

    classes_permissions = Permission.objects.filter(
        content_type__app_label="classes",
        codename__in=[
            "add_classstruct",
            "change_classstruct",
            "delete_classstruct",
            "view_classstruct",
        ]
    )

    parclass_permissions = Permission.objects.filter(
        content_type__app_label="classes",
        codename__in=[
            "add_parclass",
            "change_parclass",
            "delete_parclass",
            "view_parclass",
        ]
    )

    enums_permissions = Permission.objects.filter(
        content_type__app_label="enums",
        codename__in=[
            "add_enums",
            "change_enums",
            "delete_enums",
            "view_enums",
        ]
    )

    parprod_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "add_parprod",
            "change_parprod",
            "delete_parprod",
            "view_parprod",
        ]
    )

    prod_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "add_prod",
            "change_prod",
            "delete_prod",
            "view_prod",
        ]
    )

    parametr_permissions = Permission.objects.filter(
        content_type__app_label="parametr",
        codename__in=[
            "add_parametr",
            "change_parametr",
            "delete_parametr",
            "view_parametr",
        ]
    )

    agregat_permissions = Permission.objects.filter(
        content_type__app_label="parametr",
        codename__in=[
            "add_agregat",
            "change_agregat",
            "delete_agregat",
            "view_agregat",
        ]
    )

    handbook_executives.permissions.add(*ei_permissions)
    handbook_executives.permissions.add(*classes_permissions)
    handbook_executives.permissions.add(*parclass_permissions)
    handbook_executives.permissions.add(*enums_permissions)
    handbook_executives.permissions.add(*prod_permissions)
    handbook_executives.permissions.add(*parprod_permissions)
    handbook_executives.permissions.add(*parametr_permissions)
    handbook_executives.permissions.add(*agregat_permissions)

    # присваиваем права группе пользователей справочника
    handbook_users: Grp = (
        Group.objects
        .filter(role__code="handbook-user")
        .first()
    )

    # разрешения на просмотр моделей ClassStruct, ParClass, Ei, Prod, ParProd, Enums, Parametr
    handbook_permissions = Permission.objects.filter(
        codename__in=[
            "view_ei",
            "view_enums",
            "view_parametr",
            "view_parclass",
            "view_parprod",
            "view_prod",
            "view_classstruct",
            "view_agregat",
        ]
    )

    handbook_users.permissions.add(*handbook_permissions)

    # присваиваем права группе конструкторов
    builders: Grp = (
        Group.objects
        .filter(role__code="builder")
        .first()
    )

    builders_parametr_permissions = Permission.objects.filter(
        content_type__app_label__in="parametr",
        codename__in=[
            "can_get_total_cost_ratio",
            "can_get_product_changelog",
            "can_edit_specification",
        ]
    )

    builders_products_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "can_create_modification"
        ]
    )

    builders.permissions.add(*builders_parametr_permissions)
    builders.permissions.add(*builders_products_permissions)

    # присваиваем права группе технологов
    technologists: Grp = (
        Group.objects
        .filter(role__code="technologist")
        .first()
    )

    technologists_permissions = Permission.objects.filter(
        codename__in=[
            "add_economicactivitysubject",
            "change_economicactivitysubject",
            "delete_economicactivitysubject",
            "view_economicactivitysubject",
            "add_groupworkingcenter",
            "change_groupworkingcenter",
            "delete_groupworkingcenter",
            "view_groupworkingcenter",
            "add_prodoperation",
            "change_prodoperation",
            "delete_prodoperation",
            "view_prodoperation",
            "add_prodoperationpos",
            "change_prodoperationpos",
            "delete_prodoperationpos",
            "view_prodoperationpos",
            "add_enums",
            "change_enums",
            "delete_enums",
            "view_enums",
        ]
    )

    technologists.permissions.add(*technologists_permissions)

    # присваиваем права группе сотрудников отдела главного механика
    chief_mechanic_dept_employees: Grp = (
        Group.objects
        .filter(role__code="chief-mechanic-dept-employee")
        .first()
    )

    chief_mechanic_dept_permissions = Permission.objects.filter(
        codename__in=[
            "keep_account_of_means_of_labor",
        ]
    )

    chief_mechanic_dept_employees.permissions.add(*chief_mechanic_dept_permissions)


def remove_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    handbook_executives: Grp = Group.objects.get(code="handbook-executive")

    ei_permissions = Permission.objects.filter(
        content_type__app_label="ei",
        codename__in=[
            "add_ei",
            "change_ei",
            "delete_ei",
            "view_ei",
        ]
    )

    classes_permissions = Permission.objects.filter(
        content_type__app_label="classes",
        codename__in=[
            "add_classstruct",
            "change_classstruct",
            "delete_classstruct",
            "view_classstruct",
        ]
    )

    parclass_permissions = Permission.objects.filter(
        content_type__app_label="classes",
        codename__in=[
            "add_parclass",
            "change_parclass",
            "delete_parclass",
            "view_parclass",
        ]
    )

    enums_permissions = Permission.objects.filter(
        content_type__app_label="enums",
        codename__in=[
            "add_enums",
            "change_enums",
            "delete_enums",
            "view_enums",
        ]
    )

    parprod_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "add_parprod",
            "change_parprod",
            "delete_parprod",
            "view_parprod",
        ]
    )

    prod_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "add_prod",
            "change_prod",
            "delete_prod",
            "view_prod",
        ]
    )

    parametr_permissions = Permission.objects.filter(
        content_type__app_label="parametr",
        codename__in=[
            "add_parametr",
            "change_parametr",
            "delete_parametr",
            "view_parametr",
        ]
    )

    agregat_permissions = Permission.objects.filter(
        content_type__app_label="parametr",
        codename__in=[
            "add_agregat",
            "change_agregat",
            "delete_agregat",
            "view_agregat",
        ]
    )

    handbook_executives.permissions.remove(ei_permissions)
    handbook_executives.permissions.remove(parclass_permissions)
    handbook_executives.permissions.remove(parametr_permissions)
    handbook_executives.permissions.remove(classes_permissions)
    handbook_executives.permissions.remove(parprod_permissions)
    handbook_executives.permissions.remove(prod_permissions)
    handbook_executives.permissions.remove(enums_permissions)
    handbook_executives.permissions.remove(agregat_permissions)

    handbook_users: Grp = Group.objects.name(code="handbook-user")

    # разрешения на просмотр моделей ClassStruct, ParClass, Ei, Prod, ParProd, Enums, Parametr
    handbook_permissions = Permission.objects.filter(
        codename__in=[
            "view_ei",
            "view_enums",
            "view_parametr",
            "view_parclass",
            "view_parprod",
            "view_prod",
            "view_classstruct",
            "view_agregat",
        ]
    )

    handbook_users.permissions.remove(handbook_permissions)

    builders: Grp = Group.objects.name(code="builder")

    builders_parametr_permissions = Permission.objects.filter(
        content_type__app_label__in="parametr",
        codename__in=[
            "can_get_total_cost_ratio",
            "can_get_product_changelog",
            "can_edit_specification",
        ]
    )

    builders_products_permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "can_create_modification"
        ]
    )

    builders.permissions.remove(builders_products_permissions)
    builders.permissions.remove(builders_parametr_permissions)

    technologists: Grp = Group.objects.name(code="technologist")

    technologists_permissions = Permission.objects.filter(
        codename__in=[
            "add_economicactivitysubject",
            "change_economicactivitysubject",
            "delete_economicactivitysubject",
            "view_economicactivitysubject",
            "add_groupworkingcenter",
            "change_groupworkingcenter",
            "delete_groupworkingcenter",
            "view_groupworkingcenter",
            "add_prodoperation",
            "change_prodoperation",
            "delete_prodoperation",
            "view_prodoperation",
            "add_prodoperationpos",
            "change_prodoperationpos",
            "delete_prodoperationpos",
            "view_prodoperationpos",
            "add_enums",
            "change_enums",
            "delete_enums",
            "view_enums",
        ]
    )

    technologists.permissions.remove(technologists_permissions)

    chief_mechanic_dept_employees: Grp = Group.objects.name(code="chief-mechanic-dept-employee")

    chief_mechanic_dept_permissions = Permission.objects.filter(
        codename__in=[
            "keep_account_of_means_of_labor",
        ]
    )

    chief_mechanic_dept_employees.permissions.remove(chief_mechanic_dept_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_create_roles"),
    ]

    operations = [
        migrations.RunPython(
            code=assign_permissions,
            reverse_code=remove_permissions,
        )
    ]
