# Generated by Django 5.2 on 2026-09-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_assign_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ("name",),
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание роли"),
        ),
    ]
