# Generated by Django 5.2 on 2026-09-30 17:35

from django.db import migrations
from django.db.models import Model


def assign_permissions(apps, schema_editor):
    Group: Model = apps.get_model("auth", "Group")
    Permission: Model = apps.get_model("auth", "Permission")

    technologist = (
        Group.objects
        .filter(role__code="technologist")
        .first()
    )

    eas_permissions = Permission.objects.filter(
        content_type__app_label="economicactivitysubject",
    )

    gwc_permissions = Permission.objects.filter(
        content_type__app_label="groupworkingcenter",
    )

    prodoperation_permissions = Permission.objects.filter(
        content_type__app_label="prodoperation",
    )

    prodoperationpos_permissions = Permission.objects.filter(
        content_type__app_label="prodoperationpos",
    )

    technologist_permissions = (
        *eas_permissions,
        *gwc_permissions,
        *prodoperation_permissions,
        *prodoperationpos_permissions,
    )

    technologist.permissions.add(*technologist_permissions)

def remove_permissions(apps, schema_editor):
    Group: Model = apps.get_model("auth", "Group")
    Permission: Model = apps.get_model("auth", "Permission")

    technologist = (
        Group.objects
        .filter(role__code="technologist")
        .first()
    )

    eas_permissions = Permission.objects.filter(
        content_type__app_label="economicactivitysubject",
    )

    gwc_permissions = Permission.objects.filter(
        content_type__app_label="groupworkingcenter",
    )

    prodoperation_permissions = Permission.objects.filter(
        content_type__app_label="prodoperation",
    )

    prodoperationpos_permissions = Permission.objects.filter(
        content_type__app_label="prodoperationpos",
    )

    technologist.permissions.remove(*eas_permissions)
    technologist.permissions.remove(*gwc_permissions)
    technologist.permissions.remove(*prodoperation_permissions)
    technologist.permissions.remove(*prodoperationpos_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_role_options_alter_role_description"),
        ("route_tech", "0008_create_prodcomponent_change_trigger"),
    ]

    operations = [
        migrations.RunPython(
            code=assign_permissions,
            reverse_code=remove_permissions,
        )
    ]
