# Generated by Django 5.2 on 2026-10-01 13:46

from django.db import migrations


def assign_permissions(apps, schema_editor):
    Group: Model = apps.get_model("auth", "Group")
    Permission: Model = apps.get_model("auth", "Permission")

    technologist = (
        Group.objects
        .filter(role__code="technologist")
        .first()
    )

    permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "view_prod",
        ]
    )

    technologist.permissions.add(*permissions)


def remove_permissions(apps, schema_editor):
    Group: Model = apps.get_model("auth", "Group")
    Permission: Model = apps.get_model("auth", "Permission")

    technologist = (
        Group.objects
        .filter(role__code="technologist")
        .first()
    )

    permissions = Permission.objects.filter(
        content_type__app_label="products",
        codename__in=[
            "view_prod",
        ]
    )

    technologist.permissions.remove(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_assing_permissions_part_2"),
        ("products", "__latest__"),
    ]

    operations = [
        migrations.RunPython(
            code=assign_permissions,
            reverse_code=remove_permissions,
        )
    ]
