# Generated by Django 5.2 on 2026-08-17 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0008_prod_cost_prod_modification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.SmallIntegerField(
                        verbose_name="Позиция дочернего изделия к родительскому"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(verbose_name="Количество дочернего изделия"),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_prod",
                        to="products.prod",
                        verbose_name="Дочернее изделие",
                    ),
                ),
                (
                    "parent_prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_prod",
                        to="products.prod",
                        verbose_name="Родительское изделие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка спецификации изделия",
                "verbose_name_plural": "Строки спецификации изделия",
            },
        ),
    ]
