# Generated by Django 5.2 on 2026-08-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodcomponent",
            name="quantity",
            field=models.FloatField(verbose_name="Количество дочернего изделия"),
        ),
        migrations.CreateModel(
            name="SpecificationLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата и время внесения изменения",
                    ),
                ),
                (
                    "old_quantity",
                    models.FloatField(verbose_name="Старое количество изделия"),
                ),
                (
                    "new_quantity",
                    models.FloatField(verbose_name="Новое количество изделия"),
                ),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="specifications.prodcomponent",
                        verbose_name="Пара <Родительское изделие - Дочернее изделие>",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в истории изменений спецификации изделия",
                "verbose_name_plural": "Запись в истории изменений спецификации изделия",
            },
        ),
    ]
