# Generated by Django 5.2 on 2026-08-17 17:17

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0002_alter_prodcomponent_quantity_specificationlogs"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.IS_PARENT_PROD,
            reverse_sql=DatabaseFunctions.DROP_IS_PARENT_PROD
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.TOTAL_COST_RATIO,
            reverse_sql=DatabaseFunctions.DROP_TOTAL_COST_RATIO
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.GET_CHANGE_LOG,
            reverse_sql=DatabaseFunctions.DROP_GET_CHANGE_LOG,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.CREATE_MODIFICATION,
            reverse_sql=DatabaseFunctions.DROP_CREATE_MODIFICATION,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.PRODUCT_SPECIFICATION,
            reverse_sql=DatabaseFunctions.DROP_PRODUCT_SPECIFICATION
        )
    ]
