# Generated by Django 5.2 on 2026-08-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0003_add_sql_functions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specificationlogs",
            name="pair",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="specifications.prodcomponent",
                verbose_name="Пара <Родительское изделие - Дочернее изделие>",
            ),
        ),
    ]
