# Generated by Django 5.2 on 2026-09-07 14:03

import specifications.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0004_alter_specificationlogs_pair"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodcomponent",
            name="quantity",
            field=models.DecimalField(
                decimal_places=specifications.constants.ProdComponentConsts[
                    "DECIMAL_PLACES"
                ],
                max_digits=specifications.constants.ProdComponentConsts["MAX_DIGITS"],
                verbose_name="Количество дочернего изделия",
            ),
        ),
    ]
