# Generated by Django 5.2 on 2026-09-07 14:34

import specifications.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0006_change_functions_signatures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specificationlogs",
            name="new_quantity",
            field=models.DecimalField(
                decimal_places=specifications.constants.ProdComponentConsts[
                    "DECIMAL_PLACES"
                ],
                max_digits=specifications.constants.ProdComponentConsts["MAX_DIGITS"],
                verbose_name="Новое количество изделия",
            ),
        ),
        migrations.AlterField(
            model_name="specificationlogs",
            name="old_quantity",
            field=models.DecimalField(
                decimal_places=specifications.constants.ProdComponentConsts[
                    "DECIMAL_PLACES"
                ],
                max_digits=specifications.constants.ProdComponentConsts["MAX_DIGITS"],
                verbose_name="Старое количество изделия",
            ),
        ),
    ]
