# Generated by Django 5.2 on 2026-09-07 14:38

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0007_alter_specificationlogs_new_quantity_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.DROP_PRODUCT_SPECIFICATION,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.PRODUCT_SPECIFICATION,
            reverse_sql=DatabaseFunctions.DROP_PRODUCT_SPECIFICATION
        )
    ]
