# Generated by Django 5.2 on 2026-09-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0008_change_product_specification_signature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prodcomponent",
            options={
                "permissions": [
                    (
                        "can_get_total_cost_ratio",
                        "Может производить расчет норм расхода материальных ресурсов",
                    ),
                    (
                        "can_get_product_changelog",
                        "Может получить историю изменений спецификации изделия",
                    ),
                    (
                        "can_edit_specification",
                        "Может редактировать спецификацию изделия",
                    ),
                ],
                "verbose_name": "Строка спецификации изделия",
                "verbose_name_plural": "Строки спецификации изделия",
            },
        ),
    ]
