# Generated by Django 5.2 on 2026-09-29 14:17

from django.db import migrations

from core.queries import DatabaseFunctions


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0009_alter_prodcomponent_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DatabaseFunctions.DROP_TOTAL_COST_RATIO,
            reverse_sql=DatabaseFunctions.TOTAL_COST_RATIO,
        ),
        migrations.RunSQL(
            sql=DatabaseFunctions.TOTAL_COST_RATIO_NEW,
            reverse_sql=DatabaseFunctions.DROP_TOTAL_COST_RATIO_NEW,
        )
    ]
