# Generated by Django 4.2 on 2025-06-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ei', '0001_initial'),
        ('parametr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametr',
            name='par_ei',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ei.ei', verbose_name='Единица измерения параметра'),
        ),
    ]
