# Generated by Django 4.2 on 2026-06-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0007_alter_classstruct_base_ei_and_more"),
        ("parametr", "0003_alter_parametr_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametr",
            name="parametr_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_parameters",
                to="classes.classstruct",
                verbose_name="Тип параметра",
            ),
        ),
        migrations.AlterField(
            model_name="parametr",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=16,
                verbose_name="Сокращенное название параметра",
            ),
            preserve_default=False,
        ),
    ]
