# Generated by Django 5.2 on 2026-08-14 06:54

import parametr.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametr", "0004_alter_parametr_parametr_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametr",
            name="short_name",
            field=models.CharField(
                max_length=parametr.constants.ParametrConsts["SHORT_NAME_MAX_LENGTH"],
                verbose_name="Сокращенное название параметра",
            ),
        ),
    ]
