# Generated by Django 5.2 on 2026-09-29 12:17

import parametr.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametr", "0005_alter_parametr_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametr",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=parametr.constants.ParametrConsts["NAME_MAX_LENGTH"],
                verbose_name="Название параметра",
            ),
        ),
    ]
